document.write("<a href='/lcl/16901.html' target='_blank'><img src='/images/adv/026.jpg' width='197' height='100' border='0' /></a> ")
document.write("<a href='/lcl/9934.html' target='_blank'><img src='/images/adv/006.jpg' width='197' height='100' border='0' /></a> ")
document.write("<a href='/lcl/16646.html' target='_blank'><img src='/images/adv/025.jpg' width='197' height='100' border='0' /></a> ")
document.write("<a href='/lcl/17323.html' target='_blank'><img src='/images/adv/051.jpg' width='197' height='100' border='0' /></a> ")
document.write("<a href='/intro/gift.aspx' target='_blank'><img src='/images/adv/000.jpg' width='197' height='100' border='0' /></a> ")
document.write("<a href='/intro/gift.aspx' target='_blank'><img src='/images/adv/000.jpg' width='197' height='100' border='0' /></a> ")
document.write("<a href='/intro/gift.aspx' target='_blank'><img src='/images/adv/000.jpg' width='197' height='100' border='0' /></a> ")
document.write("<a href='/lcl/17281.html' target='_blank'><img src='/images/adv/050.jpg' width='197' height='100' border='0' /></a> ")