document.write("<table cellpadding=0 cellspacing=0 border=0  width=100%>")
document.write("<tr>")
document.write("<td width='25%'><a href='/fcl/16059.html' target='_blank'><img src='/images/adv/004.jpg' width='197' height='100' border='0' /></a></td>")
document.write("<td width='25%'><a href='/air/1255.html' target='_blank'><img src='/images/adv/015.jpg' width='197' height='100' border='0' /></a></td>")
document.write("<td width='25%'><a href='/lcl/9934.html' target='_blank'><img src='/images/adv/006.jpg' width='197' height='100' border='0' /></a></td>")
document.write("<td width='25%'><a href='/fcl/14826.html' target='_blank'><img src='/images/adv/022.gif' width='197' height='100' border='0' /></a></td>")
document.write("</tr>")
document.write("<tr>")
document.write("<td colspan='4' height='20px' align='center'><a href='/intro/adv.html' target='_blank'>如何在这里投放广告？</a></td>")
document.write("</tr>")
document.write("</table>")